In [3]:
#09.05.2026

In [4]:
#Data Understanding

In [5]:
import pandas as pd

In [6]:
customer=pd.read_csv("Data Generation/KartZone_Customers.csv")

In [7]:
customer

,Customer_ID,Customer_Name,Age,Gender,City,State,Region,Customer_Segment,Registration_Date,Registration_Source,Last_Login_Date,Last_Order_Date,Email,Phone,Loyalty_Score,Preferred_Category,Newsletter_Subscribed
0,C1001,Pallavi Gupta,36.0,Male,chennai,Tamil Nadu,South,regular,14/05/2022,app,07/03/2023,2023-07-03,pallavi1001@gmail.com,9553778756,78.0,Electronics,1
1,C1002,Shreya Reddy,-10.0,F,MUMBAI,maharashtra,West,New,09/25/2024,NaN,05-06-2024,18-05-2024,shreya1002@gmail.com,+91-9176667861,20.0,Electronics,Yes
2,C1003,PALLAVI DAS,32.0,Male,Hyd,Telangana,South,New,05-08-2023,instagram ad,NaN,04/12/2024,NaN,9248532577,13.0,Electronics,no
3,C1004,Shreya Patel,40.0,f,Hyderabad,NaN,south,Newcomer,28-04-2023,APP,01/12/2024,NaN,shreya1004@gmail.com,9786066793,33.0,FASHION,No
4,C1005,Aarav Dubey,35.0,FEMALE,mumbai,Maharashtra,West,PREMIUM,21-03-2020,Website,NaN,30/05/2024,aarav1005@gmail.com,8797801251,88.0,Electronics,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
customer.shape

(1035, 17)

In [9]:
customer.columns

Index(['Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City', 'State',
       'Region', 'Customer_Segment', 'Registration_Date',
       'Registration_Source', 'Last_Login_Date', 'Last_Order_Date', 'Email',
       'Phone', 'Loyalty_Score', 'Preferred_Category',
       'Newsletter_Subscribed'],
      dtype='object')

In [10]:
customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1035 entries, 0 to 1034
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Customer_ID            1020 non-null   object
 1   Customer_Name          1020 non-null   object
 2   Age                    959 non-null    float64
 3   Gender                 1020 non-null   object
 4   City                   963 non-null    object
 5   State                  910 non-null    object
 6   Region                 912 non-null    object
 7   Customer_Segment       1020 non-null   object
 8   Registration_Date      1020 non-null   object
 9   Registration_Source    954 non-null    object
 10  Last_Login_Date        825 non-null    object
 11  Last_Order_Date        794 non-null    object
 12  Email                  769 non-null    object
 13  Phone                  924 non-null    object
 14  Loyalty_Score          901 non-null    float64
 15  Preferred_Category     839 non-null    object
 16  Newsletter_Subscribed  914 non-null    object
dtypes: float64(2), object(15)
memory usage: 137.6+ KB

In [11]:
customer.isnull().sum()

Customer_ID               15
Customer_Name             15
Age                       76
Gender                    15
City                      72
State                    125
Region                   123
Customer_Segment          15
Registration_Date         15
Registration_Source       81
Last_Login_Date          210
Last_Order_Date          241
Email                    266
Phone                    111
Loyalty_Score            134
Preferred_Category       196
Newsletter_Subscribed    121
dtype: int64

In [12]:
customer.isnull().sum().sum()

np.int64(1831)

In [13]:
customer.duplicated().sum()

np.int64(34)

In [14]:
customer.nunique()

Customer_ID              1000
Customer_Name             909
Age                        95
Gender                     12
City                       30
State                      10
Region                      6
Customer_Segment           20
Registration_Date         918
Registration_Source        21
Last_Login_Date           704
Last_Order_Date           675
Email                     589
Phone                     677
Loyalty_Score              98
Preferred_Category         12
Newsletter_Subscribed       8
dtype: int64

In [15]:
customer.describe()

              Age  Loyalty_Score
count  959.000000     901.000000
mean    33.786236      44.462819
std     32.386322      22.706044
min    -20.000000       1.000000
25%     22.000000      28.000000
50%     31.000000      41.000000
75%     39.000000      62.000000
max    199.000000     100.000000

In [28]:
customer[customer.duplicated(keep=False)]

,Customer_ID,Customer_Name,Age,Gender,City,State,Region,Customer_Segment,Registration_Date,Registration_Source,Last_Login_Date,Last_Order_Date,Email,Phone,Loyalty_Score,Preferred_Category,Newsletter_Subscribed
76,C1077,Amrita Tiwari,35.0,male,New Delhi,delhi,North,at-risk,16-05-2021,Refer,2023-09-28,29-08-2023,amrita1077@gmail.com,9296542559,29.0,Electronics,Yes
136,C1137,SANJAY BOSE,24.0,MALE,MUMBAI,Maharashtra,West,Regular,2023-12-25,REFERRAL,29/02/2024,NaN,sanjay@,8326099417,36.0,Beauty,Yes
280,C1281,Seema Chatterjee,36.0,FEMALE,HYDERABAD,Telangana,South,AT-RISK,04/10/2022,App,2023-12-31,NaN,seema1281@gmail.com,9197116745,29.0,Fashion,NaN
319,C1320,Kartik Venkatesh,NaN,Female,hyderabad,Telangana,South,New,2023-03-20,NaN,2023-07-29,25/07/2023,kartik@,0000000000,33.0,fashion,No
411,C1412,Zara Venkatesh,24.0,M,Delhi,Delhi,North,AT-RISK,07/28/2020,Mobile App,15-03-2023,06-03-2023,zara1412@gmail.com,9751270017,13.0,Electronics,No
513,C1514,KAVYA SHAH,23.0,1,bangalore,Karnataka,South,Standard,10/20/2022,Mobile App,2024-03-03,07-02-2024,kavya1514@gmail.com,+91-9948381236,37.0,NaN,yes
521,C1522,PALLAVI JOSHI,36.0,1,delhi,Delhi,North,Regular,2020-11-07,organic,03/28/2024,2024-03-23,pallavi@,XXXXXXXXXX,84.0,Beauty,No
626,C1627,KARTIK BOSE,29.0,F,hyderabad,Telangana,NaN,Premium,12/29/2020,Referral,NaN,2024-11-01,kartik1627@gmail.com,9569815209,65.0,NaN,No
636,C1637,Ramesh Singh,198.0,FEMALE,BANGALORE,Karnataka,South,Premium,05/03/2020,Website,04/10/2024,NaN,NaN,+91-9322619259,66.0,BEAUTY,NaN
660,C1661,Ajay Verma,29.0,M,mumbai,Maharashtra,west,At-Risk,02/28/2021,instagram ad,09/10/2023,NaN,ajay1661@gmail.com,9794545453,9.0,NaN,no
678,C1679,Sanjay Shah,48.0,M,HYDERABAD,Telangana,NaN,Inactive,01-02-2020,app,04-04-2023,NaN,sanjay@,+91-9347389536,6.0,Home & Kitchen,Yes
737,C1738,ishaan reddy,0.0,female,Madras,Tamil Nadu,NaN,VIP,17-03-2021,Instagram Ad,22-09-2024,26/08/2024,NaN,NaN,79.0,Beauty,No
740,C1741,Gaurav Mishra,18.0,female,delhi,Delhi,North,regular,08/03/2023,Mobile App,03/03/2024,2024-02-22,gaurav1741@gmail.com,9952309783,83.0,beauty,Yes
761,C1762,Seema Menon,33.0,m,HYDERABAD,NaN,South,Standard,02-05-2024,Google,2024-07-23,29-06-2024,seema1762@gmail.com,9873878984,47.0,NaN,Yes
811,C1812,Amit Krishnan,31.0,1,NEW DELHI,Delhi,North,At-Risk,06/07/2020,app,03/30/2023,01-03-2023,amit@,XXXXXXXXXX,7.0,Home & Kitchen,No
859,C1860,Deepa Sen,45.0,2,Banglore,Karnataka,South,churned,2022-03-06,App,2022-08-05,NaN,deepa@,+91-9438081409,29.0,Home & Kitchen,No
883,C1884,priyanka mehta,49.0,Female,Bengaluru,Karnataka,South,Inactive,12-08-2021,Instagram Ad,24-04-2023,12-04-2023,NaN,9808076460,8.0,Electronics,NaN
899,C1900,RAHUL SHARMA,19.0,MALE,delhi,Delhi,North,Newcomer,27-03-2024,Google Ad,09/20/2023,17-09-2023,NaN,123,36.0,Home & Kitchen,yes
938,C1939,Ishaan Verma,34.0,F,MUMBAI,Maharashtra,West,REGULAR,03/27/2023,APP,11/26/2024,2024-11-13,ishaan.kz@yahoo.co.in,8359859956,43.0,Beauty,yes
973,C1974,Meena Iyer,26.0,M,bangalore,Karnataka,South,REGULAR,02/16/2020,Insta Ad,18-05-2024,04/27/2024,meena1974@gmail.com,NaN,40.0,electronics,NaN
1000,C1522,PALLAVI JOSHI,36.0,1,delhi,Delhi,North,Regular,2020-11-07,organic,03/28/2024,2024-03-23,pallavi@,XXXXXXXXXX,84.0,Beauty,No
1001,C1738,ishaan reddy,0.0,female,Madras,Tamil Nadu,NaN,VIP,17-03-2021,Instagram Ad,22-09-2024,26/08/2024,NaN,NaN,79.0,Beauty,No
1002,C1741,Gaurav Mishra,18.0,female,delhi,Delhi,North,regular,08/03/2023,Mobile App,03/03/2024,2024-02-22,gaurav1741@gmail.com,9952309783,83.0,beauty,Yes
1003,C1661,Ajay Verma,29.0,M,mumbai,Maharashtra,west,At-Risk,02/28/2021,instagram ad,09/10/2023,NaN,ajay1661@gmail.com,9794545453,9.0,NaN,no
1004,C1412,Zara Venkatesh,24.0,M,Delhi,Delhi,North,AT-RISK,07/28/2020,Mobile App,15-03-2023,06-03-2023,zara1412@gmail.com,9751270017,13.0,Electronics,No
1005,C1679,Sanjay Shah,48.0,M,HYDERABAD,Telangana,NaN,Inactive,01-02-2020,app,04-04-2023,NaN,sanjay@,+91-9347389536,6.0,Home & Kitchen,Yes
1006,C1627,KARTIK BOSE,29.0,F,hyderabad,Telangana,NaN,Premium,12/29/2020,Referral,NaN,2024-11-01,kartik1627@gmail.com,9569815209,65.0,NaN,No
1007,C1514,KAVYA SHAH,23.0,1,bangalore,Karnataka,South,Standard,10/20/2022,Mobile App,2024-03-03,07-02-2024,kavya1514@gmail.com,+91-9948381236,37.0,NaN,yes
1008,C1860,Deepa Sen,45.0,2,Banglore,Karnataka,South,churned,2022-03-06,App,2022-08-05,NaN,deepa@,+91-9438081409,29.0,Home & Kitchen,No
1009,C1137,SANJAY BOSE,24.0,MALE,MUMBAI,Maharashtra,West,Regular,2023-12-25,REFERRAL,29/02/2024,NaN,sanjay@,8326099417,36.0,Beauty,Yes
1010,C1812,Amit Krishnan,31.0,1,NEW DELHI,Delhi,North,At-Risk,06/07/2020,app,03/30/2023,01-03-2023,amit@,XXXXXXXXXX,7.0,Home & Kitchen,No
1011,C1077,Amrita Tiwari,35.0,male,New Delhi,delhi,North,at-risk,16-05-2021,Refer,2023-09-28,29-08-2023,amrita1077@gmail.com,9296542559,29.0,Electronics,Yes
1012,C1637,Ramesh Singh,198.0,FEMALE,BANGALORE,Karnataka,South,Premium,05/03/2020,Website,04/10/2024,NaN,NaN,+91-9322619259,66.0,BEAUTY,NaN
1013,C1974,Meena Iyer,26.0,M,bangalore,Karnataka,South,REGULAR,02/16/2020,Insta Ad,18-05-2024,04/27/2024,meena1974@gmail.com,NaN,40.0,electronics,NaN
1014,C1939,Ishaan Verma,34.0,F,MUMBAI,Maharashtra,West,REGULAR,03/27/2023,APP,11/26/2024,2024-11-13,ishaan.kz@yahoo.co.in,8359859956,43.0,Beauty,yes
1015,C1900,RAHUL SHARMA,19.0,MALE,delhi,Delhi,North,Newcomer,27-03-2024,Google Ad,09/20/2023,17-09-2023,NaN,123,36.0,Home & Kitchen,yes
1016,C1281,Seema Chatterjee,36.0,FEMALE,HYDERABAD,Telangana,South,AT-RISK,04/10/2022,App,2023-12-31,NaN,seema1281@gmail.com,9197116745,29.0,Fashion,NaN
1017,C1884,priyanka mehta,49.0,Female,Bengaluru,Karnataka,South,Inactive,12-08-2021,Instagram Ad,24-04-2023,12-04-2023,NaN,9808076460,8.0,Electronics,NaN
1018,C1762,Seema Menon,33.0,m,HYDERABAD,NaN,South,Standard,02-05-2024,Google,2024-07-23,29-06-2024,seema1762@gmail.com,9873878984,47.0,NaN,Yes
1019,C1320,Kartik Venkatesh,NaN,Female,hyderabad,Telangana,South,New,2023-03-20,NaN,2023-07-29,25/07/2023,kartik@,0000000000,33.0,fashion,No
1020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
customer[customer.duplicated(['Customer_ID','Customer_Name','Phone'],keep=False)].sort_values(by='Customer_ID',ascending=True)

,Customer_ID,Customer_Name,Age,Gender,City,State,Region,Customer_Segment,Registration_Date,Registration_Source,Last_Login_Date,Last_Order_Date,Email,Phone,Loyalty_Score,Preferred_Category,Newsletter_Subscribed
76,C1077,Amrita Tiwari,35.0,male,New Delhi,delhi,North,at-risk,16-05-2021,Refer,2023-09-28,29-08-2023,amrita1077@gmail.com,9296542559,29.0,Electronics,Yes
1011,C1077,Amrita Tiwari,35.0,male,New Delhi,delhi,North,at-risk,16-05-2021,Refer,2023-09-28,29-08-2023,amrita1077@gmail.com,9296542559,29.0,Electronics,Yes
136,C1137,SANJAY BOSE,24.0,MALE,MUMBAI,Maharashtra,West,Regular,2023-12-25,REFERRAL,29/02/2024,NaN,sanjay@,8326099417,36.0,Beauty,Yes
1009,C1137,SANJAY BOSE,24.0,MALE,MUMBAI,Maharashtra,West,Regular,2023-12-25,REFERRAL,29/02/2024,NaN,sanjay@,8326099417,36.0,Beauty,Yes
280,C1281,Seema Chatterjee,36.0,FEMALE,HYDERABAD,Telangana,South,AT-RISK,04/10/2022,App,2023-12-31,NaN,seema1281@gmail.com,9197116745,29.0,Fashion,NaN
1016,C1281,Seema Chatterjee,36.0,FEMALE,HYDERABAD,Telangana,South,AT-RISK,04/10/2022,App,2023-12-31,NaN,seema1281@gmail.com,9197116745,29.0,Fashion,NaN
1019,C1320,Kartik Venkatesh,NaN,Female,hyderabad,Telangana,South,New,2023-03-20,NaN,2023-07-29,25/07/2023,kartik@,0000000000,33.0,fashion,No
319,C1320,Kartik Venkatesh,NaN,Female,hyderabad,Telangana,South,New,2023-03-20,NaN,2023-07-29,25/07/2023,kartik@,0000000000,33.0,fashion,No
411,C1412,Zara Venkatesh,24.0,M,Delhi,Delhi,North,AT-RISK,07/28/2020,Mobile App,15-03-2023,06-03-2023,zara1412@gmail.com,9751270017,13.0,Electronics,No
1004,C1412,Zara Venkatesh,24.0,M,Delhi,Delhi,North,AT-RISK,07/28/2020,Mobile App,15-03-2023,06-03-2023,zara1412@gmail.com,9751270017,13.0,Electronics,No
513,C1514,KAVYA SHAH,23.0,1,bangalore,Karnataka,South,Standard,10/20/2022,Mobile App,2024-03-03,07-02-2024,kavya1514@gmail.com,+91-9948381236,37.0,NaN,yes
1007,C1514,KAVYA SHAH,23.0,1,bangalore,Karnataka,South,Standard,10/20/2022,Mobile App,2024-03-03,07-02-2024,kavya1514@gmail.com,+91-9948381236,37.0,NaN,yes
521,C1522,PALLAVI JOSHI,36.0,1,delhi,Delhi,North,Regular,2020-11-07,organic,03/28/2024,2024-03-23,pallavi@,XXXXXXXXXX,84.0,Beauty,No
1000,C1522,PALLAVI JOSHI,36.0,1,delhi,Delhi,North,Regular,2020-11-07,organic,03/28/2024,2024-03-23,pallavi@,XXXXXXXXXX,84.0,Beauty,No
626,C1627,KARTIK BOSE,29.0,F,hyderabad,Telangana,NaN,Premium,12/29/2020,Referral,NaN,2024-11-01,kartik1627@gmail.com,9569815209,65.0,NaN,No
1006,C1627,KARTIK BOSE,29.0,F,hyderabad,Telangana,NaN,Premium,12/29/2020,Referral,NaN,2024-11-01,kartik1627@gmail.com,9569815209,65.0,NaN,No
636,C1637,Ramesh Singh,198.0,FEMALE,BANGALORE,Karnataka,South,Premium,05/03/2020,Website,04/10/2024,NaN,NaN,+91-9322619259,66.0,BEAUTY,NaN
1012,C1637,Ramesh Singh,198.0,FEMALE,BANGALORE,Karnataka,South,Premium,05/03/2020,Website,04/10/2024,NaN,NaN,+91-9322619259,66.0,BEAUTY,NaN
1003,C1661,Ajay Verma,29.0,M,mumbai,Maharashtra,west,At-Risk,02/28/2021,instagram ad,09/10/2023,NaN,ajay1661@gmail.com,9794545453,9.0,NaN,no
660,C1661,Ajay Verma,29.0,M,mumbai,Maharashtra,west,At-Risk,02/28/2021,instagram ad,09/10/2023,NaN,ajay1661@gmail.com,9794545453,9.0,NaN,no
678,C1679,Sanjay Shah,48.0,M,HYDERABAD,Telangana,NaN,Inactive,01-02-2020,app,04-04-2023,NaN,sanjay@,+91-9347389536,6.0,Home & Kitchen,Yes
1005,C1679,Sanjay Shah,48.0,M,HYDERABAD,Telangana,NaN,Inactive,01-02-2020,app,04-04-2023,NaN,sanjay@,+91-9347389536,6.0,Home & Kitchen,Yes
1001,C1738,ishaan reddy,0.0,female,Madras,Tamil Nadu,NaN,VIP,17-03-2021,Instagram Ad,22-09-2024,26/08/2024,NaN,NaN,79.0,Beauty,No
737,C1738,ishaan reddy,0.0,female,Madras,Tamil Nadu,NaN,VIP,17-03-2021,Instagram Ad,22-09-2024,26/08/2024,NaN,NaN,79.0,Beauty,No
740,C1741,Gaurav Mishra,18.0,female,delhi,Delhi,North,regular,08/03/2023,Mobile App,03/03/2024,2024-02-22,gaurav1741@gmail.com,9952309783,83.0,beauty,Yes
1002,C1741,Gaurav Mishra,18.0,female,delhi,Delhi,North,regular,08/03/2023,Mobile App,03/03/2024,2024-02-22,gaurav1741@gmail.com,9952309783,83.0,beauty,Yes
761,C1762,Seema Menon,33.0,m,HYDERABAD,NaN,South,Standard,02-05-2024,Google,2024-07-23,29-06-2024,seema1762@gmail.com,9873878984,47.0,NaN,Yes
1018,C1762,Seema Menon,33.0,m,HYDERABAD,NaN,South,Standard,02-05-2024,Google,2024-07-23,29-06-2024,seema1762@gmail.com,9873878984,47.0,NaN,Yes
1010,C1812,Amit Krishnan,31.0,1,NEW DELHI,Delhi,North,At-Risk,06/07/2020,app,03/30/2023,01-03-2023,amit@,XXXXXXXXXX,7.0,Home & Kitchen,No
811,C1812,Amit Krishnan,31.0,1,NEW DELHI,Delhi,North,At-Risk,06/07/2020,app,03/30/2023,01-03-2023,amit@,XXXXXXXXXX,7.0,Home & Kitchen,No
1008,C1860,Deepa Sen,45.0,2,Banglore,Karnataka,South,churned,2022-03-06,App,2022-08-05,NaN,deepa@,+91-9438081409,29.0,Home & Kitchen,No
859,C1860,Deepa Sen,45.0,2,Banglore,Karnataka,South,churned,2022-03-06,App,2022-08-05,NaN,deepa@,+91-9438081409,29.0,Home & Kitchen,No
883,C1884,priyanka mehta,49.0,Female,Bengaluru,Karnataka,South,Inactive,12-08-2021,Instagram Ad,24-04-2023,12-04-2023,NaN,9808076460,8.0,Electronics,NaN
1017,C1884,priyanka mehta,49.0,Female,Bengaluru,Karnataka,South,Inactive,12-08-2021,Instagram Ad,24-04-2023,12-04-2023,NaN,9808076460,8.0,Electronics,NaN
1015,C1900,RAHUL SHARMA,19.0,MALE,delhi,Delhi,North,Newcomer,27-03-2024,Google Ad,09/20/2023,17-09-2023,NaN,123,36.0,Home & Kitchen,yes
899,C1900,RAHUL SHARMA,19.0,MALE,delhi,Delhi,North,Newcomer,27-03-2024,Google Ad,09/20/2023,17-09-2023,NaN,123,36.0,Home & Kitchen,yes
938,C1939,Ishaan Verma,34.0,F,MUMBAI,Maharashtra,West,REGULAR,03/27/2023,APP,11/26/2024,2024-11-13,ishaan.kz@yahoo.co.in,8359859956,43.0,Beauty,yes
1014,C1939,Ishaan Verma,34.0,F,MUMBAI,Maharashtra,West,REGULAR,03/27/2023,APP,11/26/2024,2024-11-13,ishaan.kz@yahoo.co.in,8359859956,43.0,Beauty,yes
1013,C1974,Meena Iyer,26.0,M,bangalore,Karnataka,South,REGULAR,02/16/2020,Insta Ad,18-05-2024,04/27/2024,meena1974@gmail.com,NaN,40.0,electronics,NaN
973,C1974,Meena Iyer,26.0,M,bangalore,Karnataka,South,REGULAR,02/16/2020,Insta Ad,18-05-2024,04/27/2024,meena1974@gmail.com,NaN,40.0,electronics,NaN
1020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1028,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1029,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1030,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1033,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1034,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
customer=customer.drop_duplicates(['Customer_ID','Customer_Name','Phone'])

In [35]:
customer[customer.duplicated(['Customer_ID','Customer_Name','Phone'],keep=False)].sort_values(by='Customer_ID',ascending=True)

Empty DataFrame
Columns: [Customer_ID, Customer_Name, Age, Gender, City, State, Region, Customer_Segment, Registration_Date, Registration_Source, Last_Login_Date, Last_Order_Date, Email, Phone, Loyalty_Score, Preferred_Category, Newsletter_Subscribed]
Index: []

In [36]:
customer=customer.reset_index(drop=True)

In [38]:
customer.isnull().all(axis=1).sum()

np.int64(1)

In [39]:
customer=customer.dropna(how='all')

In [40]:
customer.isnull().all(axis=1).sum()

np.int64(0)

In [45]:
customer.shape

(1000, 17)

In [49]:
(customer['Customer_Name'].str.strip()=="").sum()

np.int64(0)

In [52]:
customer['Customer_Name'].nunique()

878

In [53]:
#Remove Extra Spaces
customer['Customer_Name']=(customer['Customer_Name'].astype(str).str.strip())

#Standardize Name Format
customer['Customer_Name']=(customer['Customer_Name'].str.title())

In [54]:
customer['Customer_Name'].nunique()

807

In [55]:
customer['Customer_Name'].duplicated().sum()

np.int64(193)

In [56]:
customer[
    customer.duplicated(
        subset='Customer_Name',
        keep=False
    )
].sort_values(by='Customer_Name')[
    ['Customer_ID', 'Customer_Name']
]

    Customer_ID   Customer_Name
675       C1676     Aarav Mehta
293       C1294     Aarav Mehta
901       C1902       Aarav Rao
961       C1962       Aarav Rao
194       C1195       Aarav Sen
..          ...             ...
17        C1018        Zara Das
625       C1626     Zara Mishra
447       C1448     Zara Mishra
249       C1250  Zara Venkatesh
411       C1412  Zara Venkatesh

[358 rows x 2 columns]

In [57]:
customer['Age'].isnull().sum()

np.int64(60)

In [58]:
customer['Age'].dtype

dtype('float64')

In [59]:
customer['Age'].describe()

count    940.000000
mean      33.685106
std       32.227275
min      -20.000000
25%       22.000000
50%       31.000000
75%       39.000000
max      199.000000
Name: Age, dtype: float64

In [60]:
customer[(customer['Age']<0)|(customer['Age']>100)]

,Customer_ID,Customer_Name,Age,Gender,City,State,Region,Customer_Segment,Registration_Date,Registration_Source,Last_Login_Date,Last_Order_Date,Email,Phone,Loyalty_Score,Preferred_Category,Newsletter_Subscribed
1,C1002,Shreya Reddy,-10.0,F,MUMBAI,maharashtra,West,New,09/25/2024,NaN,05-06-2024,18-05-2024,shreya1002@gmail.com,+91-9176667861,20.0,Electronics,Yes
15,C1016,Amit Iyer,197.0,f,Delhi,Delhi,North,Regular,09/03/2021,google ad,2024-07-04,06/07/2024,NaN,9237039296,55.0,Home & Kitchen,No
24,C1025,Mr. Priya Gupta,136.0,f,Delhi,Delhi,North,Regular,2022-01-10,Website,NaN,03/10/2024,priya1025@gmail.com,9114682844,NaN,Fashion,False
39,C1040,Anjali Singh,-20.0,2,Bombay,Maharashtra,West,regular,2023-02-28,Direct,09/02/2024,NaN,anjali.kz@yahoo.co.in,9477895080,58.0,Fashion,yes
78,C1079,Zara Pillai,-8.0,FEMALE,CHENNAI,Tamil Nadu,South,New,2023-02-12,Mobile App,NaN,2024-08-08,zara1079@gmail.com,+91-9731278472,55.0,Fashion,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
949,C1950,Sonal Sen,122.0,male,MUMBAI,Maharashtra,West,regular,11/29/2021,Insta Ad,NaN,28-07-2024,sonal1950@gmail.com,9169902951,43.0,Electronics,True
967,C1968,Sneha Rao,166.0,F,BANGALORE,Karnataka,South,REGULAR,06/30/2021,Organic,06/06/2024,2024-05-18,sneha1968@gmail.com,NaN,73.0,Home & Kitchen,False
969,C1970,Isha Pillai,-8.0,f,NEW DELHI,NaN,north,NEW,2023-09-23,instagram ad,27/02/2024,13-02-2024,isha.kz@yahoo.co.in,+91-9105970150,27.0,Home & Kitchen,No
970,C1971,Lakshmi Bose,167.0,MALE,Delhi,Delhi,North,Regular,2022-09-14,website,19/11/2024,11/19/2024,lakshmi@,123,31.0,Fashion,False
992,C1993,Anjali Sharma,-10.0,F,MUMBAI,Maharashtra,West,Churned,2021-09-09,Mobile App,NaN,03/09/2022,anjali1993@gmail.com,9761877372,8.0,NaN,No

In [61]:
customer[
    (customer['Age'] < 18) |
    (customer['Age'] > 80)
]

,Customer_ID,Customer_Name,Age,Gender,City,State,Region,Customer_Segment,Registration_Date,Registration_Source,Last_Login_Date,Last_Order_Date,Email,Phone,Loyalty_Score,Preferred_Category,Newsletter_Subscribed
1,C1002,Shreya Reddy,-10.0,F,MUMBAI,maharashtra,West,New,09/25/2024,NaN,05-06-2024,18-05-2024,shreya1002@gmail.com,+91-9176667861,20.0,Electronics,Yes
10,C1011,Mr. Sonal Malhotra,0.0,female,Hyderabad,Telangana,south,new,12/07/2023,Insta Ad,26/07/2024,07/01/2024,NaN,+91-9125409494,35.0,NaN,Yes
15,C1016,Amit Iyer,197.0,f,Delhi,Delhi,North,Regular,09/03/2021,google ad,2024-07-04,06/07/2024,NaN,9237039296,55.0,Home & Kitchen,No
24,C1025,Mr. Priya Gupta,136.0,f,Delhi,Delhi,North,Regular,2022-01-10,Website,NaN,03/10/2024,priya1025@gmail.com,9114682844,NaN,Fashion,False
37,C1038,Kiran Pillai,0.0,1,Banglore,Karnataka,South,Regular,04/03/2020,NaN,01/12/2024,12/31/2023,kiran1038@gmail.com,123,34.0,Home & Kitchen,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
967,C1968,Sneha Rao,166.0,F,BANGALORE,Karnataka,South,REGULAR,06/30/2021,Organic,06/06/2024,2024-05-18,sneha1968@gmail.com,NaN,73.0,Home & Kitchen,False
969,C1970,Isha Pillai,-8.0,f,NEW DELHI,NaN,north,NEW,2023-09-23,instagram ad,27/02/2024,13-02-2024,isha.kz@yahoo.co.in,+91-9105970150,27.0,Home & Kitchen,No
970,C1971,Lakshmi Bose,167.0,MALE,Delhi,Delhi,North,Regular,2022-09-14,website,19/11/2024,11/19/2024,lakshmi@,123,31.0,Fashion,False
992,C1993,Anjali Sharma,-10.0,F,MUMBAI,Maharashtra,West,Churned,2021-09-09,Mobile App,NaN,03/09/2022,anjali1993@gmail.com,9761877372,8.0,NaN,No
995,C1996,Vijay Agarwal,0.0,Male,chennai,Tamil Nadu,south,NEW,19/06/2024,website,2023-09-02,06-08-2023,vijay1996@gmail.com,NaN,36.0,NaN,No

In [63]:
customer['Age'].value_counts().sort_index()

Age
-20.0     0.001064
-19.0     0.002128
-18.0     0.002128
-17.0     0.003191
-15.0     0.004255
            ...
 194.0    0.001064
 196.0    0.001064
 197.0    0.002128
 198.0    0.001064
 199.0    0.002128
Name: proportion, Length: 95, dtype: float64

In [67]:
customer

,Customer_ID,Customer_Name,Age,Gender,City,State,Region,Customer_Segment,Registration_Date,Registration_Source,Last_Login_Date,Last_Order_Date,Email,Phone,Loyalty_Score,Preferred_Category,Newsletter_Subscribed
0,C1001,Pallavi Gupta,36.0,Male,chennai,Tamil Nadu,South,regular,14/05/2022,app,07/03/2023,2023-07-03,pallavi1001@gmail.com,9553778756,78.0,Electronics,1
1,C1002,Shreya Reddy,-10.0,F,MUMBAI,maharashtra,West,New,09/25/2024,NaN,05-06-2024,18-05-2024,shreya1002@gmail.com,+91-9176667861,20.0,Electronics,Yes
2,C1003,Pallavi Das,32.0,Male,Hyd,Telangana,South,New,05-08-2023,instagram ad,NaN,04/12/2024,NaN,9248532577,13.0,Electronics,no
3,C1004,Shreya Patel,40.0,f,Hyderabad,NaN,south,Newcomer,28-04-2023,APP,01/12/2024,NaN,shreya1004@gmail.com,9786066793,33.0,FASHION,No
4,C1005,Aarav Dubey,35.0,FEMALE,mumbai,Maharashtra,West,PREMIUM,21-03-2020,Website,NaN,30/05/2024,aarav1005@gmail.com,8797801251,88.0,Electronics,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,C1996,Vijay Agarwal,0.0,Male,chennai,Tamil Nadu,south,NEW,19/06/2024,website,2023-09-02,06-08-2023,vijay1996@gmail.com,NaN,36.0,NaN,No
996,C1997,Kavya Singh,43.0,MALE,MUMBAI,Maharashtra,West,new,2024-06-25,organic,08-05-2024,2024-04-18,kavya1997@gmail.com,9751537654,33.0,Electronics,True
997,C1998,Aarav Joshi,32.0,1,Hyderabad,Telangana,South,NEW,2024-07-07,WEBSITE,15-03-2024,NaN,aarav1998@gmail.com,+91-9282124849,53.0,Electronics,NaN
998,C1999,Tanvi Tiwari,32.0,Male,Delhi,Delhi,NaN,PREMIUM,07-02-2020,app,NaN,2024-08-11,tanvigmail.com,0000000000,59.0,NaN,Yes
999,C2000,Vishal Sharma,32.0,Female,New Delhi,Delhi,NaN,NEW,12/30/2023,website,31-10-2023,08-10-2023,NaN,9603556843,19.0,Home & Kitchen,No

In [68]:
customer[
    (customer['Age'] >= 25) &
    (customer['Age'] <= 35)
].shape[0]

322

0        Pallavi Gupta
1         Shreya Reddy
2          PALLAVI DAS
3         Shreya Patel
4          Aarav Dubey
             ...
1030               NaN
1031               NaN
1032               NaN
1033               NaN
1034               NaN
Name: Customer_Name, Length: 1035, dtype: object

In [16]:
customer['Gender'].value_counts()

Gender
F         105
2          97
M          93
Female     88
Male       86
female     85
1          84
f          82
male       82
m          81
FEMALE     72
MALE       65
Name: count, dtype: int64